server:
  port: 8081

spring:
  # redis
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    #    password: 123456
    jedis:
      pool:
        max-idle: 100     # 最大空闲连接数
        min-idle: 0       # 最小空闲连接数
        max-active: 5000  # 最大连接数
        max-wait: 3000    # 获取连接最大等待时间，单位：ms
    timeout: 10s